Changes to resources names + update git workflow yaml

diff --git a/.github/workflows/infra-provisioning-region.yaml b/.github/workflows/infra-provisioning-region.yaml
--- a/.github/workflows/infra-provisioning-region.yaml
+++ b/.github/workflows/infra-provisioning-region.yaml
@@ -92,16 +92,23 @@ jobs:
           INSTANCE_CP_ID: ${{ env.INSTANCE_CP_ID }}
           INSTANCE_WN_IDS: ${{ env.WORKER_NODE_ID }}
 
-      - name: Cluster Initialization
+      - name: Set private key for connection
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > yaelwil-private-key.pem
           chmod 400 yaelwil-private-key.pem
-          
+
+      - name: Cluster Initialization
+        run: |
           export REGION=${{ inputs.region-code }}
           export SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
           chmod +x k8s_initializer.sh
           ./k8s_initializer.sh
-          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" -r ../k8s ubuntu@$CONTROL_PLANE_IP:~/k8s
+          
+          # SSH into the control plane to create namespaces
+          ssh -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" ubuntu@$CONTROL_PLANE_IP << EOF
+            kubectl create namespace dev || echo "Namespace 'dev' already exists"
+            kubectl create namespace prod || echo "Namespace 'prod' already exists"
+          EOF
         env:
           CONTROL_PLANE_IP: ${{ env.CONTROL_PLANE_IP }}
           
@@ -116,6 +123,137 @@ jobs:
           export KEY_PREFIX_PROD="yaelwil-certificate-pk-prod-${{ inputs.region-code }}"
           export secret_name_prod="tls-secret-prod"
           
-          # Activate the virtual environment
-          source k8s/myenv/bin/activate  
-          python3 ingress_setup.py 
+          # Copy necessary files to the control plane
+          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" -r ./k8s ubuntu@$CONTROL_PLANE_IP:~/k8s
+          
+          # SSH into the control plane to execute the TLS secret creation
+          ssh -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" ubuntu@$CONTROL_PLANE_IP << EOF
+            # Activate the virtual environment on the control plane
+            source ~/k8s/myenv/bin/activate
+            
+            # Run the Python script for ingress setup on the control plane
+            python3 ~/k8s/ingress_setup.py
+          EOF
+      - name: ConfigMap creation and copy
+        run: |
+          # Ensure the namespace exists
+          ssh -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" ubuntu@$CONTROL_PLANE_IP \
+          "kubectl create namespace ${{ inputs.environment }}" || echo 'Namespace already exists'
+
+          # Generate the ConfigMap YAML file
+          
+          cat <<EOF > polybot-dev-configmap.yaml
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: polybot-config
+            namespace: dev
+          data:
+            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
+            ALB_URL: "http://${{ inputs.app-url }}:80"
+            REGION: "${{ inputs.region-code }}"
+            BUCKET_NAME: "yaelwil-bucket-dev-${{ inputs.region-code }}-k8s-project"
+            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-dev-${{ inputs.region-code }}-k8s-project"
+            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-dev-${{ inputs.region-code }}-k8s-project.fifo"
+            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-dev-${{ inputs.region-code }}-k8s-project.fifo"
+            TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
+            CERT_PREFIX: "yaelwil-certificate-dev-${{ inputs.region-code }}"
+          EOF
+          
+          cat <<EOF > polybot-prod-configmap.yaml
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: polybot-config
+            namespace: prod
+          data:
+            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
+            ALB_URL: "http://${{ inputs.app-url }}:80"
+            REGION: "${{ inputs.region-code }}"
+            BUCKET_NAME: "yaelwil-bucket-prod-${{ inputs.region-code }}-k8s-project"
+            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-prod-${{ inputs.region-code }}-k8s-project"
+            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-prod-${{ inputs.region-code }}-k8s-project.fifo"
+            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-prod-${{ inputs.region-code }}-k8s-project.fifo"
+            TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
+            CERT_PREFIX: "yaelwil-certificate-prod-${{ inputs.region-code }}"
+          EOF
+
+          # Generate the ConfigMap YAML file
+          cat <<EOF > filters-dev-configmap.yaml
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: filters-config
+            namespace: dev
+          data:
+            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
+            ALB_URL: "http://${{ inputs.app-url }}:80"
+            REGION: "${{ inputs.region-code }}"
+            BUCKET_NAME: "yaelwil-bucket-dev-${{ inputs.region-code }}-k8s-project"
+            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-dev-${{ inputs.region-code }}-k8s-project"
+            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-dev-${{ inputs.region-code }}-k8s-project.fifo"
+            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-dev-${{ inputs.region-code }}-k8s-project.fifo"
+          EOF
+          
+          cat <<EOF > filters-prod-configmap.yaml
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: filters-config
+            namespace: prod
+          data:
+            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
+            ALB_URL: "http://${{ inputs.app-url }}:80"
+            REGION: "${{ inputs.region-code }}"
+            BUCKET_NAME: "yaelwil-bucket-prod-${{ inputs.region-code }}-k8s-project"
+            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-prod-${{ inputs.region-code }}-k8s-project"
+            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-prod-${{ inputs.region-code }}-k8s-project.fifo"
+            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-prod-${{ inputs.region-code }}-k8s-project.fifo"
+          EOF
+
+          # Generate the ConfigMap YAML file
+          cat <<EOF > yolo-dev-configmap.yaml
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: yolo-config
+            namespace: dev
+          data:
+            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
+            ALB_URL: "http://${{ inputs.app-url }}:80"
+            REGION: "${{ inputs.region-code }}"
+            BUCKET_NAME: "yaelwil-bucket-dev-${{ inputs.region-code }}-k8s-project"
+            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-dev-${{ inputs.region-code }}-k8s-project"
+            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-dev-${{ inputs.region-code }}-k8s-project.fifo"
+            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-dev-${{ inputs.region-code }}-k8s-project.fifo"
+          EOF
+          
+          cat <<EOF > yolo-prod-configmap.yaml
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: yolo-config
+            namespace: prod
+          data:
+            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
+            ALB_URL: "http://${{ inputs.app-url }}:80"
+            REGION: "${{ inputs.region-code }}"
+            BUCKET_NAME: "yaelwil-bucket-prod-${{ inputs.region-code }}-k8s-project"
+            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-prod-${{ inputs.region-code }}-k8s-project"
+            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-prod-${{ inputs.region-code }}-k8s-project.fifo"
+            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-prod-${{ inputs.region-code }}-k8s-project.fifo"
+          EOF
+
+          # Securely copy files to the remote server
+          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" filters-dev-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/FiltersMicroservice
+          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" filters-prod-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/FiltersMicroservice
+          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" polybot-dev-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/PolybotMicroservice
+          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" polybot-prod-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/PolybotMicroservice
+          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" yolo-dev-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/YoloMicroservice
+          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" yolo-prod-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/YoloMicroservice
+
+          # Clean up the private key
+          rm yaelwil-private-key.pem
+        env:
+          CONTROL_PLANE_IP: ${{ env.CONTROL_PLANE_IP }}
+          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
